### ISSUE TITLE
feat: add basic workflow pipeline

### ISSUE THREAD

**Issue by jsam** [jsam/gears#3]
To define the pipeline we could use the following manifest:

```
version: 1

pipelines:

  mypipeline:
  
    version: 0.1.0
    description: my awesome data pipeline
    
    gears:
      mygear1:
       entrypoint: ./gear.py
       function: myfunction
       selectors: []
       values:
         DatabaseHost: localhost
         DatabasePort: 6543
       requirements:
       - numpy==1.19.4
      
      mygear2:
        entrypoint: ./gear.py
        function: func2
        selectors: []
```

`dg pipeline add`

`dg pipeline list`

`dg pipeline remove`
